### ISSUE TITLE
Error executing `examples/klevr.py` 

### ISSUE THREAD

**Issue by taiya** [google-research/kubric#102]
Adding this example to the root `README.md`, so it should probably run effortlessly?
```
~/dev/kubric: docker pull docker pull kubricdockerhub/kubruntu^C
~/dev/kubric: docker run --rm --interactive \
    --user $(id -u):$(id -g) \
    --volume "$PWD:/kubric" \
    kubricdockerhub/kubruntu \
    python3 examples/klevr.py

pybullet build time: May 14 2021 21:59:35
INFO:kubric.utils:{ 'assets_dir': 'gs://kubric-public/KuBasic',
  'camera_jitter': 1.0,
  'floor_color': 'gray',
  'floor_friction': 0.3,
  'frame_end': 24,
  'frame_rate': 12,
  'frame_start': 1,
  'height': 256,
  'job_dir': 'output',
  'light_jitter': 1.0,
  'logging_level': 'INFO',
  'max_num_objects': 10,
  'min_num_objects': 3,
  'object_colors': 'clevr',
  'object_sizes': 'clevr',
  'object_types': ['Cube', 'Cylinder', 'Sphere'],
  'scratch_dir': '/tmp/tmp8yjr_51j',
  'seed': None,
  'step_rate': 240,
  'width': 256}
Traceback (most recent call last):
  File "examples/klevr.py", line 81, in <module>
    elif strategy == "clevr":
  File "/usr/local/lib/python3.7/site-packages/kubric/utils.py", line 89, in setup_directories
    if scratch_dir.exists():
AttributeError: 'str' object has no attribute 'exists'
```

**Comment by taiya** [comment]
Also, @Qwlouse should we add a pointer to the script that takes the render output and generates the GIF? (i.e. how to parse the output)

**Comment by taiya** [comment]
Obsolete
