### ISSUE TITLE
Increase efficiency of conversion process (maybe?)

### ISSUE THREAD

**Issue by taiya** [google-research/kubric#132]
- [x] Check average resource utilization of full pipeline in single thread
- [x] Check ETA for exeuction on a ~100 core [machine](https://pantheon.corp.google.com/compute/instancesDetail/zones/us-central1-a/instances/shapenet2kubric?project=kubric-xgcp)

**Comment by taiya** [comment]
`launch convert2` over 10 runs seems to only use `150%` (out of 600%) of my machine (i.e. likely single core)

**Comment by taiya** [comment]
Processing machine specs (80 vCPU)
```
gcloud compute instances create shapenet2kubric --project=kubric-xgcp --zone=us-central1-a --machine-type=n2-highcpu-80 --network-interface=network-tier=PREMIUM,subnet=default --maintenance-policy=MIGRATE --service-account=427313706792-compute@developer.gserviceaccount.com --scopes=https://www.googleapis.com/auth/cloud-platform --image=debian-10-buster-v20210721 --image-project=debian-cloud --boot-disk-size=1000GB --boot-disk-type=pd-balanced --boot-disk-device-name=shapenet2kubric --no-shielded-secure-boot --shielded-vtpm --shielded-integrity-monitoring --reservation-affinity=any
```

**Comment by taiya** [comment]
Completed execution in ~8 hours in total, pasting stdout here for reference:
```
atagliasacchi@shapenet2kubric:/home/shared/kubric/shapenet2kubric$ ./launch parfor 80
  docker run --rm --interactive --user `id -u`:`id -g` --volume $PWD:/shapenet2kubric --volume /home/shared/datasets/ShapeNetCore.v2:/ShapeNetCore.v2 kubricdockerhub/shapenet:latest python3.7 parfor.py --datadir /ShapeNetCore.v2 --num_processes 80 --stop_after 0  
pybullet build time: Jul 29 2021 07:13:24
WARNING:root:logging DEBUG+ to "/ShapeNetCore.v2/convert2.log"
WARNING:root:logging WARNING+ to stderr
  9%|▊         | 4579/52427 [44:40<4:43:20,  2.81it/s] 

  9%|▉         | 4782/52427 [46:40<4:34:18,  2.89it/s]WARNING:trimesh:vertex_normals are all set to zero!
 17%|█▋        | 8969/52427 [1:36:47<11:59:51,  1.01it/s]WARNING:trimesh:failed to load image
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/trimesh/exchange/obj.py", line 337, in parse_mtl
    util.wrap_as_stream(file_data))
  File "/usr/local/lib/python3.7/dist-packages/PIL/Image.py", line 3024, in open
    "cannot identify image file %r" % (filename if filename else fp)
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x7faf5d5efef0>
 20%|██        | 10574/52427 [2:05:28<20:43:43,  1.78s/it]



 24%|██▎       | 12336/52427 [2:27:20<9:32:58,  1.17it/s]  

 29%|██▉       | 15114/52427 [2:52:02<3:46:59,  2.74it/s] 

 32%|███▏      | 16680/52427 [3:00:40<2:29:15,  3.99it/s]
 40%|████      | 21033/52427 [3:34:27<5:40:07,  1.54it/s]WARNING:trimesh:vertex_normals are all set to zero!
 41%|████▏     | 21649/52427 [3:39:25<5:44:21,  1.49it/s]

 43%|████▎     | 22541/52427 [3:45:29<2:44:41,  3.02it/s] WARNING:trimesh:failed to load image
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/trimesh/exchange/obj.py", line 337, in parse_mtl
    util.wrap_as_stream(file_data))
  File "/usr/local/lib/python3.7/dist-packages/PIL/Image.py", line 3024, in open
    "cannot identify image file %r" % (filename if filename else fp)
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x7faf5aea2830>
 43%|████▎     | 22665/52427 [3:46:11<2:45:02,  3.01it/s]

 47%|████▋     | 24419/52427 [3:59:55<4:05:41,  1.90it/s]

 55%|█████▍    | 28710/52427 [4:34:13<2:17:30,  2.87it/s] 

 78%|███████▊  | 40968/52427 [6:08:45<5:30:57,  1.73s/it]WARNING:trimesh:failed to load image
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/trimesh/exchange/obj.py", line 337, in parse_mtl
    util.wrap_as_stream(file_data))
  File "/usr/local/lib/python3.7/dist-packages/PIL/Image.py", line 3024, in open
    "cannot identify image file %r" % (filename if filename else fp)
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x7faf671072f0>
 85%|████████▌ | 44600/52427 [6:29:40<56:00,  2.33it/s]  

 86%|████████▌ | 45132/52427 [6:33:27<54:06,  2.25it/s]  
 99%|█████████▊| 51708/52427 [7:30:22<04:16,  2.80it/s]WARNING:trimesh:vertex_normals are all set to zero!
WARNING:trimesh:failed to load image
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/trimesh/exchange/obj.py", line 337, in parse_mtl
    util.wrap_as_stream(file_data))
  File "/usr/local/lib/python3.7/dist-packages/PIL/Image.py", line 3024, in open
    "cannot identify image file %r" % (filename if filename else fp)
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x7faf5fcfe8f0>
WARNING:trimesh:failed to load image
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/trimesh/exchange/obj.py", line 337, in parse_mtl
    util.wrap_as_stream(file_data))
  File "/usr/local/lib/python3.7/dist-packages/PIL/Image.py", line 3024, in open
    "cannot identify image file %r" % (filename if filename else fp)
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x7faf5fcfe470>
100%|██████████| 52427/52427 [7:33:12<00:00,  1.93it/s]
```

**Comment by taiya** [comment]
Relaunching:
```
.../kubric/shapenet2kubric: launch -- --interactive
Fire is starting a Python REPL with the following objects:
Modules: fire, os, re, subprocess, sys
Objects: BLENDER_EXEC, CHAIR_MODEL, Path, RIFLE_MODEL, SHAPENET_ROOT, bash, blender, completion, component, convert, launch, parfor, result, trace

Python 3.7.3 (default, Jan 22 2021, 20:04:44) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> parfor(num_processes=75, stages=[0,1,2,3,4], shapenet_root=/home/shared/datasets/ShapeNetCore.v2)
```

**Comment by taiya** [comment]
Alright, seems the disagreement between sar and mpstat is just due to [bad argument defaults](https://www.unix.com/shell-programming-and-scripting/217545-mpstat-sar.html).

```
.../datasets/ShapeNetCore.v2: mpstat 5
Linux 4.19.0-17-cloud-amd64 (shapenet2kubric)   08/05/21        _x86_64_        (80 CPU)

21:55:46     CPU    %usr   %nice    %sys %iowait    %irq   %soft  %steal  %guest  %gnice   %idle
21:55:51     all   97.25    0.00    1.55    0.01    0.00    0.01    0.00    0.00    0.00    1.19
21:55:56     all   97.16    0.00    1.23    0.00    0.00    0.01    0.00    0.00    0.00    1.59
21:56:01     all   96.15    0.00    1.44    0.00    0.00    0.06    0.00    0.00    0.00    2.35
```
