### ISSUE TITLE
stage4: computation of simulation properties

### ISSUE THREAD

**Issue by taiya** [google-research/kubric#133]
According to the mesh that is used, the properties computed by trimesh are (as one would expect) completely different:
```
~/dev/kubric/shapenet2kubric: /usr/local/bin/python3 /Users/atagliasacchi/dev/kubric/shapenet2kubric/trimesh_utils.py
properties computed from /Users/atagliasacchi/datasets/ShapeNetCore.v2/04090263/18807814a9cefedcd957eaf7f4edb205/models/model_normalized.obj
{'density': 1.0, 'friction': 0.0, 'nr_vertices': 2702, 'nr_faces': 11818, 'bounds': [[-0.088758, -0.189805, -0.470597], [0.062576, 0.081813, 0.479836]], 'area': 1.211441, 'volume': 0.0, 'mass': 0.0, 'center_mass': [0.0, 0.0, 0.0], 'inertia': [[-0.0, 0.0, -0.0], [0.0, -0.0, 0.0], [-0.0, 0.0, -0.0]], 'is_convex': False, 'euler_number': 5966}
~/dev/kubric/shapenet2kubric: /usr/local/bin/python3 /Users/atagliasacchi/dev/kubric/shapenet2kubric/trimesh_utils.py
properties computed from /Users/atagliasacchi/datasets/ShapeNetCore.v2/04090263/18807814a9cefedcd957eaf7f4edb205/kubric/model_watertight.obj
{'density': 1.0, 'friction': 0.0, 'nr_vertices': 49474, 'nr_faces': 98964, 'bounds': [[-0.088758, -0.189806, -0.470597], [0.062576, 0.081813, 0.479836]], 'area': 0.489822, 'volume': 0.008007, 'mass': 0.008007, 'center_mass': [-0.001048, -0.057131, 0.170435], 'inertia': [[0.000425, 0.0, 1e-06], [0.0, 0.000409, 2.6e-05], [1e-06, 2.6e-05, 2.7e-05]], 'is_convex': False, 'euler_number': -8}
~/dev/kubric/shapenet2kubric: /usr/local/bin/python3 /Users/atagliasacchi/dev/kubric/shapenet2kubric/trimesh_utils.py
properties computed from /Users/atagliasacchi/datasets/ShapeNetCore.v2/04090263/18807814a9cefedcd957eaf7f4edb205/kubric/collision_geometry.obj
{'density': 1.0, 'friction': 0.0, 'nr_vertices': 373, 'nr_faces': 678, 'bounds': [[-0.089784, -0.190832, -0.471623], [0.064173, 0.082186, 0.480862]], 'area': 0.690398, 'volume': 0.009663, 'mass': 0.009663, 'center_mass': [-0.002462, -0.055768, 0.160321], 'inertia': [[0.000525, 1e-06, 4e-06], [1e-06, 0.000505, 3.2e-05], [4e-06, 3.2e-05, 3.5e-05]], 'is_convex': True, 'euler_number': 34}
~/dev/kubric/shapenet2kubric: 
```

@Qwlouse which one should we use? (in the legacy script it was the `model_normalized.obj`)
I would guess for physics we should use either the watertight or the collision?
And what about **Friction/Density**?

**Comment by taiya** [comment]
On another note:
1) what is the point of the per-tar JSON? (as the meshes are constant)
```
  # --- TODO(klausg): aren't these heavily redundant? (always the same)
  properties["paths"] = {
    "visual_geometry": 'visual_geometry.glb',
    "collision_geometry": 'collision_geometry.obj',
    "urdf": 'object.urdf',
  }
```

2) what is the point of the per-dataset JSON? (as this information could be extracted by a post-process scan over the data)

**Comment by taiya** [comment]
0. drop properties, and keep the ones (mass, box, inertia, volume, density, friction) from the collision proxies
1. per-tar JSON needed to support different modes of visual geometry (obj vs. GLTF)
2. per-dataset JSON used by Kubric to avoid linear scan (needs post-parfor step to collect information → new issue)

**Comment by taiya** [comment]
Just committed a change that uses `collision_geometry.obj` to compute centermass, inertia, ...
Left `friction=0.5` and `density=1.0` as per our discussion.

e.g.
```
~/dev/kubric/shapenet2kubric: launch convert2
  docker run --rm --interactive --user `id -u`:`id -g` --volume $PWD:/shapenet2kubric --volume /Users/atagliasacchi/datasets/ShapeNetCore.v2:/ShapeNetCore.v2 kubricdockerhub/shapenet:latest python3.7 convert2.py --datadir=/ShapeNetCore.v2 --model=04090263/18807814a9cefedcd957eaf7f4edb205  
pybullet build time: Jul 31 2021 19:13:21
pipeline running on "/ShapeNetCore.v2/04090263/18807814a9cefedcd957eaf7f4edb205"
stage0 running on "/ShapeNetCore.v2/04090263/18807814a9cefedcd957eaf7f4edb205"
stage1 running on "/ShapeNetCore.v2/04090263/18807814a9cefedcd957eaf7f4edb205"
stage2 running on "/ShapeNetCore.v2/04090263/18807814a9cefedcd957eaf7f4edb205"
stage3 running on "/ShapeNetCore.v2/04090263/18807814a9cefedcd957eaf7f4edb205"
stage4 running on "/ShapeNetCore.v2/04090263/18807814a9cefedcd957eaf7f4edb205"
```

produces `/Users/atagliasacchi/datasets/ShapeNetCore.v2/04090263/18807814a9cefedcd957eaf7f4edb205/kubric/data.json` with content:
```
{
    "bounds": [
        [
            -0.089784,
            -0.190832,
            -0.471623
        ],
        [
            0.064173,
            0.082186,
            0.480862
        ]
    ],
    "center_mass": [
        -0.002462,
        -0.055768,
        0.160321
    ],
    "density": 1,
    "friction": 0.5,
    "id": "04090263/18807814a9cefedcd957eaf7f4edb205",
    "inertia": [
        [
            0.000525,
            1e-06,
            4e-06
        ],
        [
            1e-06,
            0.000505,
            3.2e-05
        ],
        [
            4e-06,
            3.2e-05,
            3.5e-05
        ]
    ],
    "mass": 0.009663,
    "paths": {
        "collision_geometry": "collision_geometry.obj",
        "urdf": "object.urdf",
        "visual_geometry": "visual_geometry.glb"
    }
}
```

@Qwlouse close this issue if this to your liking.
Changes submitted to 8a3f2374234faee081418e835dde9496e0f75681

**Comment by taiya** [comment]
During the large scale launch it seems trimesh encountered some (sparse) errors.
However, as they were just logged to STDOUT, these were not captured (and not even logged!):

```
atagliasacchi@shapenet2kubric:/home/shared/kubric/shapenet2kubric$ ./launch parfor 80
  docker run --rm --interactive --user `id -u`:`id -g` --volume $PWD:/shapenet2kubric --volume /home/shared/datasets/ShapeNetCore.v2:/ShapeNetCore.v2 kubricdockerhub/shapenet:latest python3.7 parfor.py --datadir /ShapeNetCore.v2 --num_processes 80 --stop_after 0  
pybullet build time: Jul 29 2021 07:13:24
WARNING:root:logging DEBUG+ to "/ShapeNetCore.v2/convert2.log"
WARNING:root:logging WARNING+ to stderr
  9%|▊         | 4579/52427 [44:40<4:43:20,  2.81it/s] 
  9%|▉         | 4782/52427 [46:40<4:34:18,  2.89it/s]WARNING:trimesh:vertex_normals are all set to zero!
 17%|█▋        | 8969/52427 [1:36:47<11:59:51,  1.01it/s]WARNING:trimesh:failed to load image
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/trimesh/exchange/obj.py", line 337, in parse_mtl
    util.wrap_as_stream(file_data))
  File "/usr/local/lib/python3.7/dist-packages/PIL/Image.py", line 3024, in open
    "cannot identify image file %r" % (filename if filename else fp)
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x7faf5d5efef0>
 20%|██        | 10574/52427 [2:05:28<20:43:43,  1.78s/it]
 24%|██▎       | 12336/52427 [2:27:20<9:32:58,  1.17it/s]  
 29%|██▉       | 15114/52427 [2:52:02<3:46:59,  2.74it/s] 
 32%|███▏      | 16680/52427 [3:00:40<2:29:15,  3.99it/s]
 40%|████      | 21033/52427 [3:34:27<5:40:07,  1.54it/s]WARNING:trimesh:vertex_normals are all set to zero!
 41%|████▏     | 21649/52427 [3:39:25<5:44:21,  1.49it/s]
 43%|████▎     | 22541/52427 [3:45:29<2:44:41,  3.02it/s] WARNING:trimesh:failed to load image
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/trimesh/exchange/obj.py", line 337, in parse_mtl
    util.wrap_as_stream(file_data))
  File "/usr/local/lib/python3.7/dist-packages/PIL/Image.py", line 3024, in open
    "cannot identify image file %r" % (filename if filename else fp)
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x7faf5aea2830>
 43%|████▎     | 22665/52427 [3:46:11<2:45:02,  3.01it/s]
 47%|████▋     | 24419/52427 [3:59:55<4:05:41,  1.90it/s]
 47%|████▋     | 24603/52427 [4:02:26<6:30:46,  1.19it/s]
 ```

Commit 9906f393fba8d5f2d7e9e6d3f604ef83eee9568f adds logic that **should** capture this (to be verified):
```
def get_object_properties(obj_path:Path):
  with io.StringIO() as fstdout: #< scratch file buffer 
    with redirect_stdout(fstdout): #< captures python stdout
      with redirect_stderr(fstdout): #< captures python stderr
        tmesh = _get_tmesh(str(obj_path))
```

**Comment by taiya** [comment]
Relaunched modified logic (stage3: properties) with
`/home/shared/kubric/shapenet2kubric$ ./launch parfor 75 [3,] /home/shared/datasets/ShapeNetCore.v2`
