### ISSUE TITLE
exception at end of `make examples/lfn`

### ISSUE THREAD

**Issue by taiya** [google-research/kubric#161]
→ `kubric/assets/asset_source.py`

```
INFO:root:Collecting and storing metadata for each object.
INFO:root:Writing to 'output/metadata.json'
INFO:root:Done!
Exception ignored in: <function AssetSource.__del__ at 0x7fc6c6b4af70>
Traceback (most recent call last):
  File "/workspace/kubric/assets/asset_source.py", line 52, in __del__
  File "/usr/local/lib/python3.9/dist-packages/tensorflow_datasets/core/utils/gpath.py", line 141, in rmtree
AttributeError: 'NoneType' object has no attribute 'io'
Error: Not freed memory blocks: 1, total unfreed memory 0.001259 MB
```

**Comment by Qwlouse** [comment]
Was a problem with `AssetSource.__del__`. Should hopefully be fixed now.

**Comment by Chang-shuaishuai** [comment]
How to solve this problem? please
