### ISSUE TITLE
No module named `thefuzz`

### ISSUE THREAD

**Issue by taiya** [google-research/kubric#190]
```
~/dev/kubric: make examples/helloworld
docker run --rm --interactive --user `id -u`:`id -g` --volume `pwd`:/workspace kubricdockerhub/kubruntudev python3 examples/helloworld.py
Traceback (most recent call last):
  File "/workspace/examples/helloworld.py", line 16, in <module>
    import kubric as kb
  File "/workspace/kubric/__init__.py", line 57, in <module>
    from kubric import assets
  File "/workspace/kubric/assets/__init__.py", line 15, in <module>
    from .asset_source import AssetSource, ClosableResource
  File "/workspace/kubric/assets/asset_source.py", line 23, in <module>
    import thefuzz.process
ModuleNotFoundError: No module named 'thefuzz'
make: *** [Makefile:49: examples/helloworld] Error 1
```

**Comment by taiya** [comment]
- `requirements.txt` seems to already contain `thefuzz`
- edited `KubruntuDev.Dockerfile` to modify workdir/path
- rebuilt image `make kubruntudev`
- pushed image `make kubruntudev/push`
