### ISSUE TITLE
Bug in kb.assets.utils.add_hdri_dome

### ISSUE THREAD

**Issue by ziyuw** [google-research/kubric#192]
When calling the function the following error occured:

`Traceback (most recent call last):
  File "/kubric/challenges/multiview_matting/worker.py", line 210, in <module>
    dome = kb.assets.utils.add_hdri_dome(hdri_source, scene, background_hdri)
  File "/usr/local/lib/python3.9/dist-packages/kubric/assets/utils.py", line 98, in add_hdri_dome
    dome_path = hdri_source.fetch("dome.blend")
TypeError: fetch() missing 1 required positional argument: 'asset_id`

**Comment by ziyuw** [comment]
This is the offending line: https://github.com/google-research/kubric/blob/3f216bd800c76a96f3fa44a4bc2dcc5bda0a2604/kubric/assets/utils.py#L98

**Comment by Qwlouse** [comment]
Ah, goood catch, that function should be updated or removed. The dome was moved to be an asset in KuBasic and can be added like this:
``` python
# Add Dome object
dome = kubasic.create(asset_id="dome", name="dome", static=True, background=True)
scene += dome
# Set the texture 
dome_blender = dome.linked_objects[renderer]
texture_node = dome_blender.data.materials[0].node_tree.nodes["Image Texture"]
texture_node.image = bpy.data.images.load(background_hdri_filename)
```
