### ISSUE TITLE
Importing ActorCore Ready assets and the like

### ISSUE THREAD

**Issue by MrXandbadas** [google-research/kubric#222]
Hey there,
I was wondering if anyone could assist me in how we should handle assets like ActorCore Assets and Animations inside of Kubric?

i'm trying to run the "export_assets_from_blend.py" and receive the following error. Could it be that I don't have the information laid out correctly inside of blender?

Log:

INFO:root:Clearing / resetting Blender...

INFO:root:Opening 'uploads_files_1939375_Casual_Male.blend' ...
INFO:root:Exporting the Objects collection to directory 'E:kubricUbuntukubricexamplesKodieobjects'
/workspace/kubric/assets/asset_preprocessing.py:65: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is 
a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 
'dtype=object' when creating the ndarray.
  faces = np.array([list(p.vertices) for p in bmesh.polygons if len(p.vertices) > 2])  # pylint: disable=unnecessary-comprehension        
Kubricifying casual_male...
Applying scale and rotation transformations...
Converting and validating...
Read blend: uploads_files_1939375_Casual_Male.blend
TypeError: int() argument must be a string, a bytes-like object or a number, not 'list'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/workspace/export_assets_from_blend.py", line 48, in <module>
    export_collection(FLAGS.collection, FLAGS.output_dir)
  File "/workspace/kubric/assets/asset_preprocessing.py", line 309, in export_collection
    details_list.append(kubricify(output_folder, obj))
  File "/workspace/kubric/assets/asset_preprocessing.py", line 219, in kubricify
    tmesh = create_trimesh_from_obj(obj)
  File "/workspace/kubric/assets/asset_preprocessing.py", line 90, in create_trimesh_from_obj
    tmesh = trimesh.Trimesh(vertices=vertices, faces=faces)
  File "/usr/local/lib/python3.9/dist-packages/trimesh/base.py", line 127, in __init__
    self.faces = faces
  File "/usr/local/lib/python3.9/dist-packages/trimesh/base.py", line 306, in faces
    values = np.asanyarray(values, dtype=np.int64)
ValueError: setting an array element with a sequence.
make: *** [Makefile:66: model] Error 1

End Log

**Comment by Qwlouse** [comment]
I have seen this error before, but my memory is a bit fuzzy. It might be due to having n-gons in the mesh (rather than only triangles). IIRC  `trimesh` required pure-triangle meshes.
You could try the Blender triangulate method on your mesh first:
``` python
# assuming your mesh is selected
bpy.ops.object.mode_set(mode='EDIT')      # switch to mesh edit mode
bpy.ops.mesh.select_all(action='SELECT')  # select all faces
bpy.ops.mesh.quads_convert_to_tris()      # triangulate
bpy.ops.object.mode_set(mode='OBJECT')    # back to object mode
```
