### ISSUE TITLE
Error when running bouncing_balls and shapenet in examples

### ISSUE THREAD

**Issue by wangyuyy** [google-research/kubric#290]
I tried to run the bounding_balls.py and shapenet.py in examples, but the error occurred as follows.
The codes were not changed after cloning, and the codes were run in docker.
Thanks for your generous help!
```shell
# python examples/bouncing_balls.py 
2023-05-10 07:23:21.279805: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2023-05-10 07:23:21.279847: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Warning: Falling back to the standard locale ("C")
Traceback (most recent call last):
  File "/cephfs/BJ-AI/project/wangyu/kubric/examples/bouncing_balls.py", line 38, in <module>
    parser.set_defaults(frame_end=24, frame_rate=12, width=128, height=128)
  File "/usr/local/lib/python3.9/dist-packages/kubric/utils.py", line 96, in set_defaults
    assert key in valid_names, f"Specifying default for an undefined argument '{key}'"
AssertionError: Specifying default for an undefined argument 'width'
```
```shell
python examples/shapenet.py 
Warning: Falling back to the standard locale ("C")
2023-05-10 07:23:54.957348: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2023-05-10 07:23:54.957391: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
INFO:kubric.utils:{ 'frame_end': 5,
  'frame_rate': 24,
  'frame_start': 1,
  'job_dir': 'output',
  'logging_level': 'INFO',
  'resolution': (512, 512),
  'scratch_dir': '/tmp/tmpf0zy8xf4',
  'seed': None,
  'step_rate': 240}
INFO:root:Deleting content of old scratch-dir: /tmp/tmpf0zy8xf4
INFO:root:Using scratch directory: /tmp/tmpf0zy8xf4
INFO:root:Using output directory: output
Traceback (most recent call last):
  File "/cephfs/BJ-AI/project/wangyu/kubric/examples/shapenet.py", line 25, in <module>
    shapenet = kb.AssetSource.from_manifest(source_path)
  File "/usr/local/lib/python3.9/dist-packages/kubric/assets/asset_source.py", line 68, in from_manifest
    raise ValueError(f"The path `{manifest_path}` is a placeholder for the real path. "
ValueError: The path `gs://kubric-public/assets/ShapeNetCore.v2.json` is a placeholder for the real path. Please visit https://shapenet.org, agree to terms and conditions.After logging in, you will find the manifest URL here:https://shapenet.org/download/kubric
Error: Not freed memory blocks: 1, total unfreed memory 0.001259 MB
```
Besides, does the error like this matters?
```shell
Error: Not freed memory blocks: 1, total unfreed memory 0.001259 MB
```

**Comment by wangyuyy** [comment]
I solved the error when running bouncing_balls.py by ignoring the safety check of argparse.ArgumentParser.set_defaults(). But the second
```python
for key in kwargs:
      assert key in valid_names, f"Specifying default for an undefined argument '{key}'"
```

**Comment by NguyenVanThanhHust** [comment]
@wangyuyy  did you solve the first problem ?
